version: '3'

volumes:
  postgres-data:
    driver: local
  

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rubocop: &app_base
    build: .
    command: guard start --no-bundler-warning --no-interactions --plugin rubocop
    volumes:
      - .:/myapp
      
    depends_on:
      - db

  web:
    <<: *app_base
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
